### ISSUE TITLE
Can it play idle animation by default?

### ISSUE THREAD

**Issue by ghostoact** [Querijn/LeagueModel#13]
Other animations are too exaggerated.

**Comment by Querijn** [comment]
Yes, but you'll have to recompile. Remove the code below this line: https://github.com/Querijn/LeagueModel/blob/master/src/application.cpp#L235

and call Module.PlayAnimation(`path to your prefered animation`);

**Comment by ghostoact** [comment]
Can't it be configured at initialization time? XD 
 For example: canvas background, model size.

**Comment by Querijn** [comment]
It can be configured at initialization time, the code that chooses the animation is found [here](https://github.com/Querijn/LeagueModel/blob/master/src/application.cpp#L565), as you can see I just choose the first emote it finds. You can probably replace it with idle, but it might not be good, as there are a lot of animations that are "switching to idle state".

Canvas background will have to be rendered, I have no support for this. Model size can be changed but I don't scale the animation right now, meaning that some models will look weird (those with other submeshes that are relative to one another but not attached, eg swords)
