### ISSUE TITLE
the material of the model is mosaic. Is it normal?

### ISSUE THREAD

**Issue by ghostoact** [Querijn/LeagueModel#15]
Hello, I'm here again. XD. I have successfully compiled the project. **Thank you for your guidance.**

I found that the material of the model is mosaic. Is it normal? The magnification is obvious.

The screenshot is Mecha Aatrox.

![Mecha Aatrox](https://user-images.githubusercontent.com/30609680/50627900-9f026980-0f70-11e9-8b9c-057c5935e2f3.jpg)

**Comment by Querijn** [comment]
Yeah that's GL_NEAREST. Should be changable to GL_LINEAR.

Here: https://github.com/Querijn/LeagueModel/blob/master/src/renderer/texture.cpp#L147
